### ISSUE TITLE
'$mock.js' in .gitignore but it still shows in git

### ISSUE THREAD

**Issue by socketbear** [solufa/axios-mock-server#453]
## Description

I put'$mock.js' in .gitignore but it still shows in git. 'mocks/$mock.js','$mock.js','$mock.*'... I tried putting them all, but it doesn't work.
As expected, the'$' seems to be the problem.

## Describe the solution you'd like

'$mock.js' is also good, but it would be nice if it could be created with a different name via configure.

**Comment by solufa** [comment]
@socketbear 
Thank you for posting.
I've added the outputFilename option in v0.19.0.
https://github.com/solufa/axios-mock-server#configuration
